# fly.toml app configuration file generated for glerl-web-sparkling-leaf-967-muddy-breeze-72-morning-cherry-7508 on 2024-02-27T07:26:58-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'glerl-web'
primary_region = 'ord'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'glerl-web.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
